
#include <stdio.h>

int main()
{
	int AbcdefghijklmnopAbcdefghijklmnopAbcdefghijklmnopAbcdefghijklmnopAbcdefghijklmnopAbcdefghijklmnopAbcdefghijklmnopAbcdefghijklmnopAbcdefghijklmnopAbcdefghijklmnopAbcdefghijklmnopAbcdefghijklmnopAbcdefghijklmnopAbcdefghijklmnopAbcdefghijklmnopAbcdefghijklmnop = 5;

	printf("%d\n", AbcdefghijklmnopAbcdefghijklmnopAbcdefghijklmnopAbcdefghijklmnopAbcdefghijklmnopAbcdefghijklmnopAbcdefghijklmnopAbcdefghijklmnopAbcdefghijklmnopAbcdefghijklmnopAbcdefghijklmnopAbcdefghijklmnopAbcdefghijklmnopAbcdefghijklmnopAbcdefghijklmnopAbcdefghijklmnop);

	int AbcdefghijklmnopAbcdefghijklmnopAbcdefghijklmnopAbcdefghijklmnopAbcdefghijklmnopAbcdefghijklmnopAbcdefghijklmnopAbcdefghijklmnopAbcdefghijklmnopAbcdefghijklmnopAbcdefghijklmnopAbcdefghijklmnopAbcdefghijklmnopAbcdefghijklmnopAbcdefghijklmnopAbcdefghijklmnop1 = 42;

	printf("%d\n", AbcdefghijklmnopAbcdefghijklmnopAbcdefghijklmnopAbcdefghijklmnopAbcdefghijklmnopAbcdefghijklmnopAbcdefghijklmnopAbcdefghijklmnopAbcdefghijklmnopAbcdefghijklmnopAbcdefghijklmnopAbcdefghijklmnopAbcdefghijklmnopAbcdefghijklmnopAbcdefghijklmnopAbcdefghijklmnop1);

	return 0;
}
